language: php

php:
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv config-add mongophpconfig.ini
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
  
services:
  - mongodb

cache:
  directories:
    - node_modules
    - vendor